name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug SERVER_IP
        run: |
          echo "Length: ${#SERVER_IP}"
          echo "Value starts with: ${SERVER_IP:0:5}"
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy Project Files
        run: |
          scp -i ~/.ssh/id_rsa Dockerfile index.html \
          ubuntu@${{ secrets.SERVER_IP }}:/home/ubuntu/devops-portfolio/

      - name: Deploy Container
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/ubuntu/devops-portfolio

            docker build -t portfolio .

            docker stop portfolio || true
            docker rm portfolio || true

            docker run -d --name portfolio -p 80:80 portfolio
          EOF